import 'dart:convert';
import 'dart:io';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import 'package:synchronized/synchronized.dart';
import '../model/rehab_session.dart';

final rehabRepositoryProvider = Provider((ref) => RehabSessionRepository());
final rehabSessionsProvider = FutureProvider(
  (ref) => ref.watch(rehabRepositoryProvider).load(),
);

class RehabSessionRepository {
  static const storageKey = 'rehab_daily_sessions_v1';
  static const planKey = 'rehab_daily_plan_v1';
  static final _lock = Lock();
  Future<List<RehabSession>> load() async {
    final raw = (await SharedPreferences.getInstance()).getString(storageKey);
    if (raw == null) return [];
    // Do not overwrite corrupt data with an empty history.
    final values = jsonDecode(raw) as List;
    return values
        .map((v) => RehabSession.fromJson(Map<String, dynamic>.from(v as Map)))
        .toList()
      ..sort((a, b) => b.startedAt.compareTo(a.startedAt));
  }

  Future<void> save(RehabSession session) => _lock.synchronized(() async {
    final all = await load();
    all.removeWhere((s) => s.id == session.id);
    all.insert(0, session);
    await _write(all);
  });
  Future<void> _write(List<RehabSession> all) async {
    if (!await (await SharedPreferences.getInstance()).setString(
      storageKey,
      jsonEncode(all.map((s) => s.toJson()).toList()),
    )) {
      throw StateError('Could not save practice');
    }
  }

  Future<void> savePlan(String scenarioId, int repetitions) async {
    if (!await (await SharedPreferences.getInstance()).setString(
      planKey,
      jsonEncode({'scenarioId': scenarioId, 'repetitions': repetitions}),
    )) {
      throw StateError('Could not save plan');
    }
  }

  Future<({String scenarioId, int repetitions})> loadPlan() async {
    final raw = (await SharedPreferences.getInstance()).getString(planKey);
    if (raw == null) return (scenarioId: 'rest', repetitions: 1);
    final j = jsonDecode(raw) as Map;
    return (
      scenarioId: j['scenarioId'] as String,
      repetitions: (j['repetitions'] as int).clamp(1, 3),
    );
  }

  Future<bool> delete(String id) => _lock.synchronized(() async {
    final all = await load();
    final removed = all
        .where((s) => s.id == id)
        .expand((s) => s.takes)
        .toList();
    final remaining = all.where((s) => s.id != id).toList();
    final used = remaining.expand((s) => s.takes).map((t) => t.path).toSet();
    final documents = (await getApplicationDocumentsDirectory()).path;
    final dirs = {
      'recordings',
      'voice_analysis',
    }.map((name) => p.normalize(p.join(documents, name))).toSet();
    // Commit the record change before unlinking audio; a failed write must not destroy it.
    await _write(remaining);
    var cleaned = true;
    // Only unlink assets generated by the new daily player, never imported paths.
    for (final take in removed) {
      if (used.contains(take.path) ||
          !dirs.contains(p.dirname(p.normalize(take.path))) ||
          !p.basename(take.path).startsWith('rehab_')) {
        continue;
      }
      final file = File(take.path);
      try {
        if (await file.exists()) await file.delete();
      } on FileSystemException {
        cleaned = false;
      }
    }
    return cleaned;
  });
}
